### ISSUE TITLE
Gotop on alpine can't use busybox ps

### ISSUE THREAD

**Issue by maxice8** [cjbassi/gotop#138] opened 2019-04-22 13:17 UTC
Required information:

- gotop version (`gotop -V`): 3.0.0
- The output of `uname -a`: Linux Impreza 4.19.34-0-vanilla #1-Alpine SMP Mon Apr 8 06:03:08 UTC 2019 x86_64 Linux
- Terminal emulator (e.g. iTerm or gnome terminal): Alacritty
- Any relevenat hardware info: None
- tmux version if using tmux: No

Also please copy or attach `~/.local/state/gotop/errors.log` if it exists and contains logs:

13:15:31 proc_linux.go:14: failed to retrieve processes: failed to execute 'ps' command: exit status 1
13:15:32 proc_linux.go:14: failed to retrieve processes: failed to execute 'ps' command: exit status 1

![image](https://user-images.githubusercontent.com/30738253/56502154-c2cdc900-64e7-11e9-85d1-d01458a7db32.png)

**Comment by maxice8** [comment] 2019-04-22 13:18
Very similar to #134 but i didn't put it there since one is FreeBSD and the other is Alpine Linux

**Comment by maxice8** [comment] 2019-04-22 13:18
Installing `procps` which provides a widely used `ps` works around it. but it would be nice if it worked with the `busybox ps`.

![image](https://user-images.githubusercontent.com/30738253/56502230-0294b080-64e8-11e9-9fe5-bc0ec9120b3e.png)

**Comment by cjbassi** [comment] 2019-04-22 18:01
Duplicate of #110, but thanks for the addition information. This gave me some new ideas which I'll post in that issue.

**Closed by cjbassi** 2019-04-22 18:01 UTC
