### ISSUE TITLE
Crash due to SIGSEGV in Disk widget update due to ignored error return

### ISSUE THREAD

**Issue by thefloweringash** [cjbassi/gotop#64] opened 2018-10-15 01:14 UTC
Stack trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x52108c]

goroutine 24 [running]:
github.com/cjbassi/gotop/src/widgets.(*Disk).update(0xc000244000)
	/build/go/src/github.com/cjbassi/gotop/src/widgets/disk.go:90 +0x60c
github.com/cjbassi/gotop/src/widgets.NewDisk(0x0)
	/build/go/src/github.com/cjbassi/gotop/src/widgets/disk.go:42 +0x177
main.initWidgets.func5()
	/build/go/src/github.com/cjbassi/gotop/main.go:252 +0x22
created by main.initWidgets
	/build/go/src/github.com/cjbassi/gotop/main.go:251 +0xdb
```

Analysis:

The return value of `psDisk.Usage(Part.Mount)` ([disk.go:89][]) may include an error value. This value is ignored, and `nil` is returned as `usage`, which is immediately dereferenced.

With some printf debugging:
```
Testing usage of /var/lib/docker
usage={"path":"/var/lib/docker","fstype":"zfs","total":137729015808, [...]
err=<nil>

Testing usage of /var/lib/docker/zfs/graph/ff22819000f48b6f19cb17f41c389840cb3f0feb44de3aaffc6af0569ec7246f
usage=<nil>
err=permission denied
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x52141c]
``` 

[disk.go:89]: https://github.com/cjbassi/gotop/blob/32e257dc1c6b1e7db778e184d617bf9128f04990/src/widgets/disk.go#L89

Please give the following info:

- The output of `uname -a`: `Linux altenberg 4.14.74 #1-NixOS SMP Thu Oct 4 00:01:00 UTC 2018 x86_64 GNU/Linux`
- Any relevenat hardware info: regular desktop system
- Terminal shell (like zsh or bash): zsh
- Terminal emulator (like iTerm or gnome terminal): iTerm
- tmux version if using tmux: n/a

**Comment by simoniz0r** [comment] 2018-10-24 23:10
A couple of other people I've talked to have the same problem when having an NTFS or FAT32 partition mounted.  This seems to be a problem with the file systems of mounted partitions.  `gotop` does not seem to support Windows file systems at all.

**Comment by Snuggle** [comment] 2018-10-24 23:10
This bug is affecting multiple users. Causes gotop to crash and be unusable for me when I have a bootable SD card (Fat32) inserted into my computer. It's also affecting my friend when they have an NTFS external HDD plugged in.

**Comment by cjbassi** [comment] 2018-12-05 06:50
1. I just added more logging to the master branch so you should be able to check `~/.config/gotop/log` when this issue occurs.
2. This may be the same issue as #41 and #39, which were caused by unescaped space characters in partition mountpoints, so it only occurred when mountpoints had spaces in their names. That issue has since been fixed, so if anyone could try the master branch and report if they are still having this issue, then that would be great.

**Comment by thefloweringash** [comment] 2018-12-06 04:10
The "permission denied" error is still crashing:

```
$ ./bin/gotop                                                                          ~/go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x522c32]

goroutine 10 [running]:
github.com/cjbassi/gotop/src/widgets.(*Disk).update(0xc0001ac140)
	/home/lorne/go/src/github.com/cjbassi/gotop/src/widgets/disk.go:101 +0x702
github.com/cjbassi/gotop/src/widgets.NewDisk(0x0)
	/home/lorne/go/src/github.com/cjbassi/gotop/src/widgets/disk.go:43 +0x173
main.initWidgets.func5(0xc00001b120)
	/home/lorne/go/src/github.com/cjbassi/gotop/main.go:217 +0x22
created by main.initWidgets
	/home/lorne/go/src/github.com/cjbassi/gotop/main.go:216 +0x11e
```

```
13:08:32 disk.go:99: failed to get partition usage statistics from gopsutil: permission denied. Part: &{zroot/docker/b405434046d6a2225a29c9dd81c81742718b7aedac290e536c4ad6af912fe2f7 /var/lib/docker/zfs/graph/b405434046d6a2225a29c9dd81c81742718b7aedac290e536c4ad6af912fe2f7 0 0   0 }
```

**Comment by cjbassi** [comment] 2018-12-06 04:15
Okay, good to know. I'll have to create an issue over at gopsutil.

**Comment by thefloweringash** [comment] 2018-12-08 06:31
I don't think this is a gopsutil issue. The [`Usage`](https://github.com/shirou/gopsutil/blob/35815938bff48222524b5954ccf69ddef700b1e8/disk/disk_unix.go#L21) function uses the `statfs` syscall, and that syscall is returning failure, which gopsutil is propagating correctly.

```
$ strace -f -e trace=statfs ./go/bin/gotop
...
statfs("/var/lib/docker/zfs/graph/70944229e0b82d08f5e0db3db9ce20f90e222ec8d2e36e960019745778c0f586", 0xc0000b5958) = -1 EACCES (Permission denied)
```

**Comment by cjbassi** [comment] 2018-12-08 08:04
@thefloweringash Thanks for pointing out your findings. I realize now that I should probably do more sleuthing of my own before dumping these issues onto someone else.

I also went down a rabbit hole of researching syscalls and `/var/lib/docker/` and the issue seems pretty straight forward now.

1) In your example, the argument being passed to `statfs` is a path to a docker container filesystem.
2) We don't have permissions to access dockers resources at `/var/lib/docker/`, which is why we get an error.

I think in general, gotop shouldn't display docker container filesystems, and it should also ignore filesystems it doesn't have permission to interact with. So overall a pretty easy fix.

**Comment by cjbassi** [comment] 2018-12-08 08:43
So I just pushed a change to master that should fix the panic. One thing I'm curious about is whether `gopsutil.Partitions()` is bugged, since calling it with `false` should only return physical devices. This might be because you have the zfs storage driver set up for docker, which could be interfering with gopsutil's check on the filesystem type of the mounted partition. Could you run the latest commit from master and give me the log outputs from `~/.config/gotop/log` and also test if it works? Thanks!

**Comment by thefloweringash** [comment] 2018-12-08 09:42
With the current version I do not get panics, just an entry with empty stats. :+1:

The errors are the same as before:
```
18:41:03 disk.go:100: failed to get partition usage statistics from gopsutil: permission denied. Part: &{zfast/docker/6269fa6c800d21b1a149a1e4a2193ecf3310839e0580c470f4a6f9f9a1c5ff27 /var/lib/docker/zfs/graph/6269fa6c800d21b1a149a1e4a2193ecf3310839e0580c470f4a6f9f9a1c5ff27 0 0   0 }
```

**Comment by cjbassi** [comment] 2018-12-10 19:18
That's good to hear. I just pushed 67e0fedbede63e9155bc74d9df739c12fb5e7562 to master which should make it so the entry doesn't show up at all. I think I'll close this issue, but if anyone has any more issues with certain disks not showing up or showing up with empty stats then feel free to create a new issue. Also thanks @thefloweringash for helping solve this issue!

**Closed by cjbassi** 2018-12-10 19:18 UTC
Labels: bug
